module Rank
  RANKS = {
    sap: { name: 'Sapeur',
           image_path: 'ranks/sapeur.png' },
    cal: { name: 'Caporal',
           image_path: 'ranks/caporal.png' },
    cch: { name: 'Caporal-chef',
           image_path: 'ranks/caporal-chef.png' },
    sgt: { name: 'Sergent',
           image_path: 'ranks/sergent.png' },
    scc: { name: 'Sergent-chef',
           image_path: 'ranks/sergent-chef.png' },
    adj: { name: 'Adjudant',
           image_path: 'ranks/adjudant.png' },
    adc: { name: 'Adjudant-chef',
           image_path: 'ranks/adjudant-chef.png' },
    mjr: { name: 'Major',
           image_path: 'ranks/major.png' },
    lt: { name: 'Lieutenant',
          image_path: 'ranks/lieutenant.png' },
    cne: { name: 'Capitaine',
           image_path: 'ranks/capitaine.png' },
    cdt: { name: 'Commandant',
           image_path: 'ranks/commandant.png' },
    lcl: { name: 'Lieutenant - colonel',
           image_path: 'ranks/lieutenant-colonel.png' },
    col: { name: 'Colonel',
           image_path: 'ranks/colonel.png' }
  }
end
